---
title: "S6 - LFO-CV Case 1"
output: 
  html_document:
    toc: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(cmdstanr)
library(furrr)
library(dplyr)
library(readr)
library(progressr)
library(purrr)
library(rstan)
library(tictoc)
library(tidyr)
library(stringr)

source("./R_scripts/ELDP.R")
source("./R_scripts/model_selection.R")
source("./R_scripts/LFO_CV.R")
source("./R_scripts/log_funs.R")
source("./R_scripts/plots.R")
source("./R_scripts/utils.R")
source("./R_scripts/tables.R")

MLE_results <- read_csv("./Saved_objects/Inference/Synthetic_data/SEIR/Case_1/MLE_choice.csv")
```


```{r}
y_df <- read_csv("./data/Synthetic/SEIR/Case_1.csv")
```

## Latent states

```{r}
plot_ts_by_I_order(y_df)
```


## Measurements


```{r}
ggplot(y_df, aes(time, y)) +
  geom_line(aes(group = dataset), colour = "grey75", alpha = 0.1) +
  facet_wrap("I_order") +
  theme_pubr()
```

# Leave-future-out cross-validation (LFO-CV)

```{r} 
n_chains          <- 4
samples_per_chain <- 1000
n_samples         <- n_chains * samples_per_chain
M_m               <- 1
M_n               <- 1:4
L_min             <- 5 # minimum number of points

root_fldr <- "./Saved_objects/LFO_CV/Synthetic_data/Case_1"

info_files <- readRDS("./Stan_files/SEIR/Pois/meta_info.rds")
meas_mdl   <- "pois"

global_end_points <- vector(mode = "list", length = length(M_n))
LFO_CV_default    <- vector(mode = "list", length = length(M_n))
LFO_CV_optim      <- vector(mode = "list", length = length(M_n))
```

## First-order data

```{r}
D_m      <- 1
D_n      <- 1
n_data   <- 20

create_backup_fldrs(D_m, D_n, n_data, M_m, M_n, root_fldr)
```

```{r}
all_fits <- CV_datasets(n_data, y_df, D_n, M_n, L_min, n_chains, 
                        samples_per_chain, root_fldr, meas_mdl)
```


```{r}
L_max    <- 57
fp       <- str_glue("{root_fldr}/D{D_m}{D_n}/L_analysis_all.csv")
L_df     <- evaluate_L(n_data, y_df, D_n, M_n, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```

```{r}
 plot_error_by_L(L_df)
```

```{r}
 plot_min_error(L_df, 0, "sqr_error")
```

```{r}
error_df <- L_df |> filter(error <= min(error) + 0) |> 
  mutate(range = L_max - L_min) |> arrange(desc(range))

bounds <- error_df |> slice(1) |> select(L_min, L_max) |> as.numeric()

global_end_points[[D_n]] <- bounds

print(error_df)
```

```{r}
ELDP_default          <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, L_min, 
                                     L_min, meas_mdl, L_max) 
LFO_CV_default[[D_n]] <- ELDP_default

ELDP_best           <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, 
                                   bounds[[1]], L_min, meas_mdl, bounds[[2]])
LFO_CV_optim[[D_n]] <- ELDP_best
```

```{r, message = FALSE}
plot_prediction_comparison(ELDP_default, ELDP_best, MLE_results, D_n)
```

### Stepwise choice

```{r}
M_n_list <- c(1:2)
fp       <- str_glue("{root_fldr}/D1{D_n}/L_analysis_1_2.csv")

L_df     <- evaluate_L(n_data, y_df, D_n, M_n_list, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```

```{r}
plot_error_by_L(L_df)
```

```{r}
plot_CV_boundary(y_df, D_n, 5, 31)
```


```{r}
ELDP_df <- ELDP_choice(n_data, y_df, D_n, M_n_list, all_fits, 20, L_min, 
                       meas_mdl, 43)

data.frame(D_n = D_n, 
           n_sucesses = sum(ELDP_df$is_correct), 
           error      = sum(ELDP_df$error),
           sqrt_error = sum(ELDP_df$sqrt_error))
```

```{r}
ELDP_df <- ELDP_choice(n_data, y_df, D_n, M_n_list, all_fits, 26, L_min, 
                       meas_mdl, 35)

data.frame(D_n = D_n, 
           n_sucesses = sum(ELDP_df$is_correct), 
           error      = sum(ELDP_df$error),
           sqrt_error = sum(ELDP_df$sqrt_error))
```


## Second-order data

```{r}
D_m      <- 1
D_n      <- 2
n_data   <- 20

create_backup_fldrs(D_m, D_n, n_data, M_m, M_n, root_fldr)
```

```{r}
all_fits <- CV_datasets(n_data, y_df, D_n, M_n, L_min, n_chains, 
                        samples_per_chain, root_fldr, meas_mdl)
```

```{r}
L_max    <- 54
fp       <- str_glue("{root_fldr}/D{D_m}{D_n}/L_analysis_all.csv")
L_df     <- evaluate_L(n_data, y_df, D_n, M_n, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```


```{r}
plot_error_by_L(L_df)
```

```{r}
plot_min_error(L_df, 0, "sqr_error")
```

```{r}
error_df <- L_df |> filter(error <= min(error) + 0) |> 
  mutate(range = L_max - L_min) |> arrange(desc(range))

bounds <- error_df |> slice(1) |> select(L_min, L_max) |> as.numeric()

global_end_points[[D_n]] <- bounds

print(error_df)
```


```{r}
ELDP_default          <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, L_min, 
                                     L_min, meas_mdl, L_max) 
LFO_CV_default[[D_n]] <- ELDP_default

ELDP_best           <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, 
                                   bounds[[1]], L_min, meas_mdl, bounds[[2]])
LFO_CV_optim[[D_n]] <- ELDP_best
```

```{r, message = FALSE}
plot_prediction_comparison(ELDP_default, ELDP_best, MLE_results, D_n)
```

## Stepwise selection

```{r}
M_n_list <- c(1:2)
fp       <- str_glue("{root_fldr}/D1{D_n}/L_analysis_1_2.csv")
L_df     <- evaluate_L(n_data, y_df, D_n, M_n_list, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```

```{r}
plot_error_by_L(L_df)
```

```{r}
plot_CV_boundary(y_df, D_n, 5, 15)
```

```{r}
ELDP_df <- ELDP_choice(n_data, y_df, D_n, M_n_list, all_fits, 20, L_min, 
                       meas_mdl, 46)

data.frame(D_n = D_n, 
           n_sucesses = sum(ELDP_df$is_correct), 
           error      = sum(ELDP_df$error),
           sqrt_error = sum(ELDP_df$sqrt_error))
```

```{r}
ELDP_df <- ELDP_choice(n_data, y_df, D_n, M_n_list, all_fits, 27, L_min, 
                       meas_mdl, L_max)

data.frame(D_n = D_n, 
           n_sucesses = sum(ELDP_df$is_correct), 
           error      = sum(ELDP_df$error),
           sqrt_error = sum(ELDP_df$sqrt_error))
```

## Third-order data

```{r}
D_m      <- 1
D_n      <- 3
n_data   <- 20

create_backup_fldrs(D_m, D_n, n_data, M_m, M_n, root_fldr)
```

```{r all_fit_3}
all_fits <- CV_datasets(n_data, y_df, D_n, M_n, L_min, n_chains, 
                        samples_per_chain, root_fldr, meas_mdl)
```

```{r}
L_max    <- 50
fp       <- str_glue("{root_fldr}/D1{D_n}/L_analysis_all.csv")
L_df     <- evaluate_L(n_data, y_df, D_n, M_n, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```

```{r}
plot_error_by_L(L_df)
```


```{r}
plot_min_error(L_df, 0, "sqr_error")
```

```{r}
error_df <- L_df |> filter(error <= min(error) + 0) |> 
  mutate(range = L_max - L_min) |> arrange(desc(range))

bounds <- error_df |> slice(1) |> select(L_min, L_max) |> as.numeric()

global_end_points[[D_n]] <- bounds

print(error_df)
```

```{r}
ELDP_default          <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, L_min, 
                                     L_min, meas_mdl, L_max) 
LFO_CV_default[[D_n]] <- ELDP_default

ELDP_best           <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, 
                                   bounds[[1]], L_min, meas_mdl, bounds[[2]])
LFO_CV_optim[[D_n]] <- ELDP_best
```

```{r, message = FALSE}
plot_prediction_comparison(ELDP_default, ELDP_best, MLE_results, D_n)
```

```{r}
M_n_list <- c(1:2)
fp       <- str_glue("{root_fldr}/D1{D_n}/L_analysis_1_2.csv")
L_df     <- evaluate_L(n_data, y_df, D_n, M_n_list, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```

```{r}
plot_error_by_L(L_df)
```

```{r}
plot_min_error(L_df, 3)
```

```{r}
L_df |> filter(error <= min(error) + 2) |> mutate(range = L_max - L_min) |> arrange(desc(range))
```

```{r}
ELDP_df <- ELDP_choice(n_data, y_df, D_n, M_n_list, all_fits, 24, L_min, 
                       meas_mdl, 50)

data.frame(D_n = D_n, 
           n_sucesses = sum(ELDP_df$is_correct), 
           error      = sum(ELDP_df$error),
           sqrt_error = sum(ELDP_df$sqrt_error))
```

## Fourth-order data

```{r}
D_m      <- 1
D_n      <- 4
n_data   <- 20

create_backup_fldrs(D_m, D_n, n_data, M_m, M_n, root_fldr)
```

```{r all_fit_4}
all_fits <- CV_datasets(n_data, y_df, D_n, M_n, L_min, n_chains, 
                        samples_per_chain, root_fldr, meas_mdl)
```

```{r}
L_max    <- 49
fp       <- str_glue("{root_fldr}/D1{D_n}/L_analysis_all.csv")
L_df  <- evaluate_L(n_data, y_df, D_n, M_n, all_fits, L_min, L_max, 
                    meas_mdl, fp)
```

```{r}
plot_error_by_L(L_df)
```

```{r}
plot_min_error(L_df, 1, "sqr_error")
```

```{r}
error_df <- L_df |> filter(error <= min(error) + 1) |> 
  mutate(range = L_max - L_min) |> arrange(desc(range))

bounds <- error_df |> slice(1) |> select(L_min, L_max) |> as.numeric()

global_end_points[[D_n]] <- bounds

print(error_df)
```


```{r}
ELDP_default          <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, L_min, 
                                     L_min, meas_mdl, L_max) 
LFO_CV_default[[D_n]] <- ELDP_default

ELDP_best           <- ELDP_choice(n_data, y_df, D_n, M_n, all_fits, 
                                   bounds[[1]], L_min, meas_mdl, bounds[[2]])
LFO_CV_optim[[D_n]] <- ELDP_best
```

```{r, message = FALSE}
plot_prediction_comparison(ELDP_default, ELDP_best, MLE_results, D_n)
```

```{r}
M_n_list <- c(1:2)
fp       <- str_glue("{root_fldr}/D1{D_n}/L_analysis_1_2.csv")
L_df     <- evaluate_L(n_data, y_df, D_n, M_n_list, all_fits, L_min, L_max, 
                       meas_mdl, fp)
```

```{r}
plot_error_by_L(L_df)
```

```{r}
plot_min_error(L_df, 1)
```

```{r}
L_df |> filter(error <= min(error) + 1) |> mutate(range = L_max - L_min) |> arrange(desc(range))
```

```{r}
ELDP_df <- ELDP_choice(n_data, y_df, D_n, M_n_list, all_fits, 5, L_min, 
                       meas_mdl, 49)

data.frame(D_n = D_n, 
           n_sucesses = sum(ELDP_df$is_correct), 
           error      = sum(ELDP_df$error))
```


# Summary

```{r}
summarise_predictions <- function(pred_list) {
  
   df <- do.call(rbind, pred_list) |> 
     group_by(D_n) |> 
     summarise(sqrt_error  = sum(sqrt_error),
               pct_success = sum(is_correct) / n())
   
   df
}

LFO_default_scores <- summarise_predictions(LFO_CV_default) |> 
  mutate(window = "LFO (Default)")

LFO_optim_scores <- summarise_predictions(LFO_CV_optim) |> 
  mutate(window = "LFO (Optimum)")

write_csv(LFO_optim_scores, file.path(root_fldr, "LFO_optim.csv"))

MLE_score <- estimate_MLE_score(MLE_results)

scores_df <- bind_rows(MLE_score, LFO_default_scores, LFO_optim_scores) |> 
  pivot_wider(names_from = window, values_from = c(sqrt_error, pct_success))
```

```{r}
table_comparison_scores(scores_df)
```

# Boundaries

```{r, fig.height = 7}
boundaries_df <- imap_dfr(global_end_points, \(obj, i) {
  
  data.frame(I_order = i,
             ll = obj[[1]],
             ul = obj[[2]])
})

write_csv(boundaries_df, file.path(root_fldr, "boundaries.csv"))

plot_CV_boundaries(y_df, boundaries_df)
```


